##General Configuraton
#server.port=8081
server.servlet.context-path=/products
spring.datasource.url=jdbc:mysql://localhost:3306/product_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=


##Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


##Debugging/Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true


##Circular Reference Error - Spring Boot 2.6+
spring.main.allow-circular-references=true


##Environment variables